[project]
name = "minibone"
version = "0.0.1"
description = "Small boiler plate with tools for multithreading"
authors = [
    {name = "Erick Romero", email = "erick@gjrlabs.com"}
]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: GNU AFFERO GENERAL PUBLIC LICENSE",
    "Operating System :: Os Independent",
]
requires-python = ">=3.7"
dependencies = []

[project.urls]
"Homepage" = "https://github.com/erromu/minibone/"
"Bug Tracker" = "https://github.com/erromu/minibone/issues"
